name: Build Bitcodes

on:
    push:
        paths:
            - bitcodes/**
            - .github/workflows/bitcodes.yml
    pull_request:
        paths:
            - bitcodes/**
            - .github/workflows/bitcodes.yml
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: Build LLVM artifacts
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Verify clang
              run: clang --version

            - name: Build bitcodes
              run: ./bitcodes/build.sh --force

            - name: Upload bitcode artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: bitcodes
                  path: |
                      bitcodes/bc
                      bitcodes/ll
                  if-no-files-found: error
